{{- if .Values.dataplane.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intellaro.fullname" . }}-config
  labels:
    {{- include "intellaro.labels" . | nindent 4 }}
    app.kubernetes.io/component: dataplane
data:
  config.yaml: |
    {{- tpl .Values.dataplane.config . | nindent 4 }}
{{- end }}
